sudo: false
language: php
php:
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.composer/vendor
    - vendor

before_install:
  # Update Composer
  - composer self-update

script:
  - composer install -o --prefer-dist --no-interaction

  # Check project with phps
  - composer run lint
